Simple tutorial

In [77]:
def functionToFind(x1, x2, x3):
    #y = 3 * x1**2 - 7 * x2 + 13/(x3+1)
    y = 3 * x1 - 7 * x2 + 13*x3
    return y

In [78]:
print(functionToFind(5, 1, 4))

60


In [79]:
# Create random data
number_of_samples = 1000
import random
import numpy as np
x = list(zip(random.sample(range(1000), number_of_samples), random.sample(range(1000), number_of_samples), random.sample(range(1000), number_of_samples)))
y=[]
for input in x:
    y.append(functionToFind(input[0], input[1], input[2]))
y=np.array(y)
len(x), len(y)
x,y

([(538, 114, 109),
  (582, 828, 187),
  (744, 894, 429),
  (195, 766, 399),
  (126, 219, 824),
  (102, 403, 749),
  (133, 369, 428),
  (22, 56, 473),
  (930, 242, 416),
  (820, 735, 743),
  (733, 602, 95),
  (232, 485, 350),
  (136, 8, 207),
  (326, 45, 972),
  (53, 236, 373),
  (295, 655, 99),
  (644, 9, 275),
  (612, 187, 160),
  (79, 53, 832),
  (182, 509, 979),
  (132, 944, 950),
  (926, 868, 9),
  (298, 952, 841),
  (559, 13, 104),
  (565, 399, 444),
  (522, 525, 69),
  (356, 88, 260),
  (547, 650, 954),
  (338, 580, 11),
  (748, 724, 464),
  (459, 476, 365),
  (665, 817, 569),
  (80, 848, 778),
  (312, 802, 973),
  (327, 54, 733),
  (222, 324, 278),
  (999, 669, 657),
  (170, 3, 151),
  (886, 204, 786),
  (510, 180, 157),
  (316, 259, 340),
  (996, 18, 527),
  (737, 768, 219),
  (758, 192, 267),
  (975, 951, 763),
  (940, 790, 506),
  (349, 734, 1),
  (93, 102, 101),
  (683, 535, 235),
  (828, 328, 957),
  (586, 392, 551),
  (897, 705, 262),
  (52, 579, 67),
  (176, 905, 720),
  

In [80]:
#Normalization
#from sklearn import preprocessing
#normalized_x = preprocessing.normalize(x, axis=1)

from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler

scaler_x = StandardScaler()
scaled_x = scaler_x.fit_transform(x)

scaler_y = StandardScaler()
scaled_y = scaler_y.fit_transform(y.reshape(-1,1))

scaled_x, scaled_y

C:\Program Files\Anaconda3\envs\fastai-cpu\lib\site-packages\sklearn\utils\validation.py:590: DataConversionWarning: Data with input dtype int32 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
C:\Program Files\Anaconda3\envs\fastai-cpu\lib\site-packages\sklearn\utils\validation.py:590: DataConversionWarning: Data with input dtype int32 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


(array([[ 0.13336798, -1.33541184, -1.35273236],
        [ 0.28578853,  1.13795795, -1.0825323 ],
        [ 0.84697327,  1.36658877, -0.24421929],
        ...,
        [-1.0894605 , -1.30077081, -0.47285011],
        [ 0.27539622, -1.18299129,  0.3585347 ],
        [-0.35507059, -1.61946831, -0.06062181]]), array([[-0.52930304],
        [-1.4304634 ],
        [-0.68885428],
        [-0.95578678],
        [ 1.18411816],
        [ 0.63785403],
        [-0.26096687],
        [ 0.31056344],
        [ 0.46988073],
        [ 0.5798354 ],
        [-1.23418263],
        [-0.61867045],
        [-0.3398067 ],
        [ 2.05954446],
        [-0.26658158],
        [-1.6162166 ],
        [ 0.22189787],
        [-0.4418072 ],
        [ 1.44730752],
        [ 1.21991192],
        [ 0.38425646],
        [-1.79588721],
        [ 0.15615902],
        [-0.36437104],
        [ 0.04175938],
        [-1.33524734],
        [-0.15522323],
        [ 1.16914561],
        [-1.73085019],
        [-0.3012056 ],
  

In [81]:
# y.reshape(-1,1) converts 1D array to 2D
# One shape dimension can be -1. In this case, the value is inferred from the length of the array and remaining dimensions.
y.shape, y.reshape(-1,1).shape

((1000,), (1000, 1))

In [82]:
import torch
from torch import nn
from torch import optim
import torch.nn.functional as F

Convert numpy arrays to tensors

In [83]:
x_train, y_train = map(torch.tensor, (scaled_x, scaled_y))
#x_train, y_train
print(x_train.dim(), x_train.type())
x_train = x_train.type(torch.FloatTensor)
y_train = y_train.type(torch.FloatTensor)
print(x_train.dim(), x_train.type(), len(x_train))

2 torch.DoubleTensor
2 torch.FloatTensor 1000


Create NN

In [84]:
class myModel(nn.Module):
    def __init__(self):
        #super().__init__()
        super(myModel, self).__init__() 
        # Calling Super Class's constructor
        self.lin1 = nn.Linear(3, 10)
        self.lin2 = nn.Linear(10,1)

    def forward(self, xb):
        x = F.relu(self.lin1(xb))
        return self.lin2(x)

In [85]:
def get_model(lr):
    model = myModel()
    return model, optim.SGD(model.parameters(), lr=lr)

In [86]:
loss_func = F.mse_loss #nn.MSELoss()# Mean Squared Loss

In [87]:
model, opt = get_model(1e-1)
print(loss_func(model(x_train), y_train))

tensor(1.3225, grad_fn=<MseLossBackward>)


In [88]:
print(x_train[0])
print(model(x_train[0]))

tensor([ 0.1334, -1.3354, -1.3527])
tensor([-0.5476], grad_fn=<AddBackward0>)


Train without loader

In [89]:
model, opt = get_model(1e-1)
print(f'Parameters: {model.parameters}')

n = len(x_train)
bs = 100
epochs = 7000

for epoch in range(epochs):
    for i in range((n - 1) // bs + 1):
        start_i = i * bs
        end_i = start_i + bs
        xb = x_train[start_i:end_i]
        yb = y_train[start_i:end_i]
        pred = model(xb)
        loss = loss_func(pred, yb)
        #if i==0:
        #    print(xb, pred, yb)        
        
        loss.backward()
        opt.step()
        opt.zero_grad()

    if (epoch % 100) == 0:
        print('epoch {}, loss {}'.format(epoch,loss))
            
#print(loss_func(model(xb), yb))
print(loss_func(model(x_train), y_train))

Parameters: <bound method Module.parameters of myModel(
  (lin1): Linear(in_features=3, out_features=10, bias=True)
  (lin2): Linear(in_features=10, out_features=1, bias=True)
)>
epoch 0, loss 0.3370809853076935
epoch 100, loss 0.000527826719917357
epoch 200, loss 0.00013648401363752782
epoch 300, loss 6.908543582540005e-05
epoch 400, loss 4.14049718528986e-05
epoch 500, loss 2.7740292352973484e-05
epoch 600, loss 1.9783359675784595e-05
epoch 700, loss 1.4907133845554199e-05
epoch 800, loss 1.1582416846067645e-05
epoch 900, loss 9.180388587992638e-06
epoch 1000, loss 7.476494829461444e-06
epoch 1100, loss 6.203577868291177e-06
epoch 1200, loss 5.237065579422051e-06
epoch 1300, loss 4.483644261199515e-06
epoch 1400, loss 3.8741059142921586e-06
epoch 1500, loss 3.3855669698823476e-06
epoch 1600, loss 2.979367309308145e-06
epoch 1700, loss 2.633728854561923e-06
epoch 1800, loss 2.3469992811442353e-06
epoch 1900, loss 2.099808170896722e-06
epoch 2000, loss 1.8906514469563263e-06
epoch 2100

Train using dataset and dataloader

In [92]:
from torch.utils.data import TensorDataset
from torch.utils.data import DataLoader

train_ds = TensorDataset(x_train, y_train)
train_dl = DataLoader(train_ds, batch_size=bs)

In [93]:
model, opt = get_model(1e-1)
print(f'Parameters: {model.parameters}')

n = len(x_train)
bs = 100
epochs = 7000

for epoch in range(epochs):
    for xb, yb in train_dl:
        pred = model(xb)
        loss = loss_func(pred, yb)

        loss.backward()
        opt.step()
        opt.zero_grad()
        
    if (epoch % 100) == 0:
        print('epoch {}, loss {}'.format(epoch,loss))

print(loss_func(model(xb), yb))

Parameters: <bound method Module.parameters of myModel(
  (lin1): Linear(in_features=3, out_features=10, bias=True)
  (lin2): Linear(in_features=10, out_features=1, bias=True)
)>
epoch 0, loss 0.11047697812318802
epoch 100, loss 0.001005497295409441
epoch 200, loss 0.000190821461728774
epoch 300, loss 3.5293574910610914e-05
epoch 400, loss 6.246199518500362e-06
epoch 500, loss 1.1528316008480033e-06
epoch 600, loss 2.3015546446458757e-07
epoch 700, loss 5.145170689502265e-08
epoch 800, loss 1.3768866935492952e-08
epoch 900, loss 4.4068122484475225e-09
epoch 1000, loss 1.6584364992411338e-09
epoch 1100, loss 6.996148105287148e-10
epoch 1200, loss 3.1238067688121873e-10
epoch 1300, loss 1.4558582117629726e-10
epoch 1400, loss 6.778667904772107e-11
epoch 1500, loss 3.183388275207477e-11
epoch 1600, loss 1.5382238885419675e-11
epoch 1700, loss 7.582457231536388e-12
epoch 1800, loss 3.8719743557236175e-12
epoch 1900, loss 1.9982958430336817e-12
epoch 2000, loss 1.294240647813083e-12
epoch 2

Train with validation and fit

In [102]:
def loss_batch(model, loss_func, xb, yb, opt=None):
    loss = loss_func(model(xb), yb)

    if opt is not None:
        loss.backward()
        opt.step()
        opt.zero_grad()

    return loss.item(), len(xb)

import numpy as np

# Note that we always call model.train() before training, and model.eval() before inference, 
# because these are used by layers such as nn.BatchNorm2d and nn.Dropout to ensure appropriate behaviour for these 
# different phases.

def fit(epochs, model, loss_func, opt, train_dl, valid_dl):
    for epoch in range(epochs):
        model.train()
        for xb, yb in train_dl:
            loss_batch(model, loss_func, xb, yb, opt)

        if (epoch % 100) == 0:
            model.eval()
            with torch.no_grad():
                # get the loss and number of samples for each batch in valid_dl
                losses, nums = zip(
                    *[loss_batch(model, loss_func, xb, yb) for xb, yb in valid_dl]
                )
            val_loss = np.sum(np.multiply(losses, nums)) / np.sum(nums)

            print(epoch, val_loss)

from torch.utils.data import DataLoader
        
def get_data(train_ds, valid_ds, bs):
    return (
        DataLoader(train_ds, batch_size=bs, shuffle=True),
        DataLoader(valid_ds, batch_size=bs * 2),
    )

In [104]:
from torch.utils.data import TensorDataset

train_ds = TensorDataset(x_train, y_train)
# Use the train dataset as validation, just for test not a good practice
valid_ds = TensorDataset(x_train, y_train)

train_dl, valid_dl = get_data(train_ds, valid_ds, bs)
model, opt = get_model(1e-1)
fit(epochs, model, loss_func, opt, train_dl, valid_dl)

0 0.11445724368095397
100 0.0005000436562113464
200 0.00014754814328625797
300 6.49134162813425e-05
400 3.250794288760517e-05
500 1.7880360428534913e-05
600 1.0704837586672511e-05
700 7.026666753517929e-06
800 4.911654514216934e-06
900 3.5163266602467045e-06
1000 2.5978735493481507e-06
1100 1.9359151110620585e-06
1200 1.4950248782952258e-06
1300 1.179395530925831e-06
1400 9.451603375509876e-07
1500 7.575924826142e-07
1600 6.219515000793763e-07
1700 5.139704171597259e-07
1800 4.264548891796949e-07
1900 3.602841715633076e-07
2000 3.091014747269583e-07
2100 2.652205736808355e-07
2200 2.3051077420177534e-07
2300 2.0184692672842175e-07
2400 1.7669393272967682e-07
2500 1.570772742098825e-07
2600 1.4047890175561407e-07
2700 1.2693928574947222e-07
2800 1.1513846871480382e-07
2900 1.0358665125664857e-07
3000 9.360350503584413e-08
3100 8.479078719147993e-08
3200 7.705675848512783e-08
3300 7.03676648505791e-08
3400 6.456317631631237e-08
3500 5.9459687307139574e-08
3600 5.4905308211061764e-08
3700

Evaluate

In [103]:
input = [[1.0,1.0,1.0]]
input_scaled = scaler_x.transform(input)

input_scaled = torch.tensor(input_scaled).type(torch.FloatTensor)

out = model(input_scaled)
print(out.data[0])
scaler_y.inverse_transform(out.data[0].reshape(-1,1))

tensor([-1.0496])


array([[9.08252]], dtype=float32)

In [91]:
print(functionToFind(input[0][0], input[0][1], input[0][2]))

9.0
